In [33]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download("punkt", quiet=True)
from nltk.tokenize import sent_tokenize
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments
import torch
from datasets import Dataset, DatasetDict
import evaluate
import re

In [3]:
train = pd.read_csv("C:/Users/User/Desktop/master/proyectos/doc_summ_llm/data/train.csv")
test = pd.read_csv("C:/Users/User/Desktop/master/proyectos/doc_summ_llm/data/test_features.csv")

In [4]:
train.head()

,paper_id,text,summary
0,0,## FROM SOVEREIGNTY TO EXTRATERRITORIAL CONSCI...,"In this article, Victor Fan argues that analys..."
1,1,## 1. Introduction\n\n\nAn Electronic Health R...,Problem definition: Physicians spend more than...
2,2,## Introduction\n\n\nTranslation plays an i...,Literary translation is one of the most challe...
3,3,## 1 Problem Setup\n\n\nRecent political scien...,There is a long-running debate on evaluating f...
4,4,## INTRODUCTION\n\n\nThis article investigat...,"Recently, ‘bimajyo’ (美魔女) came into focus in J..."

In [5]:
test.head()

   paper_id                                               text
0      1000  ## Introduction\n\n\nGender disparities persis...
1      1001  ## Introduction\n\n\nOne of humanity’s greates...
2      1002  ## Introduction\n\n\nHow do workers get attach...
3      1003  ## BETWEEN INDEXES AND SYMBOLS: AN EXPRESSION ...
4      1004  ## The Evolution of Environmental and Climate ...

In [6]:
train.shape

(1000, 3)

In [14]:
len(train['summary'][789])

1148

In [50]:
len_total = []
for l in train['summary']:
    len_total.append(len(l))

print(np.mean(len_total))
print(np.std(len_total))

1274.3857142857144
428.4297639672823

In [18]:
validation = train.iloc[700:]
validation.head()

,paper_id,text,summary
700,700,## Introduction\n\n\nCommon sense understandin...,Conventional interpretations of public and soc...
701,701,INTRODUCTION\n\n\nAmerican anthropology is eng...,American Anthropology is engaged in significan...
702,702,## Introduction\n\n\nSwear and taboo words in ...,The current study attempted to determine the t...
703,703,## Introduction\n\n\nAddressing attitudes is c...,Introduction\nAddressing attitudes is central ...
704,704,## Introduction\n\n\nThe concept of time is at...,It is well recognized that time-averaging of a...

In [19]:
train = train.iloc[:700]
train.shape

(700, 3)

In [20]:
validation.shape

(300, 3)

In [21]:
train.drop(columns=['paper_id'], inplace=True)
validation.drop(columns=['paper_id'], inplace=True)
test.drop(columns=['paper_id'], inplace=True)

In [22]:
train.head()

,text,summary
0,## FROM SOVEREIGNTY TO EXTRATERRITORIAL CONSCI...,"In this article, Victor Fan argues that analys..."
1,## 1. Introduction\n\n\nAn Electronic Health R...,Problem definition: Physicians spend more than...
2,## Introduction\n\n\nTranslation plays an i...,Literary translation is one of the most challe...
3,## 1 Problem Setup\n\n\nRecent political scien...,There is a long-running debate on evaluating f...
4,## INTRODUCTION\n\n\nThis article investigat...,"Recently, ‘bimajyo’ (美魔女) came into focus in J..."

In [23]:
train_ds = Dataset.from_pandas(train)
validation_ds = Dataset.from_pandas(validation)
test_ds = Dataset.from_pandas(test)

In [24]:
ds = DatasetDict({
    'train': train_ds,
    'validation': validation_ds,
})

In [25]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'summary'],
        num_rows: 700
    })
    validation: Dataset({
        features: ['text', 'summary'],
        num_rows: 300
    })
})

In [26]:
len(ds['train']['summary'][16])

1030

In [105]:
model_name = 'facebook/bart-large-cnn'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

In [106]:
model.config

BartConfig {
  "_num_labels": 3,
  "activation_dropout": 0.0,
  "activation_function": "gelu",
  "add_final_layer_norm": false,
  "architectures": [
    "BartForConditionalGeneration"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 1024,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 4096,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 12,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "dtype": "float32",
  "early_stopping": true,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 4096,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 12,
  "eos_token_id": 2,
  "force_bos_token_to_be_generated": true,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "length_penalty": 2.0,
  "max_length": 142,
  "max_position_embeddings": 1024,
  "min_length": 56,
  "model_type": "bart",
  "no_repeat_ngram_size": 3,
  "normalize_before": false,
  "num_beams": 4,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "prefix": " ",
  "scale_embedding": false,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 142,
      "min_length": 56,
      "no_repeat_ngram_size": 3,
      "num_beams": 4
    }
  },
  "transformers_version": "4.56.2",
  "use_cache": true,
  "vocab_size": 50264
}

In [87]:
tokenizer.model_max_length
tokenizer.vocab

{'▁Az': 12611,
 '▁Survey': 11418,
 'aţia': 10984,
 '▁contacter': 17987,
 '▁pret': 7140,
 'licate': 26221,
 'kamera': 28867,
 '▁courant': 16203,
 '▁landscape': 3283,
 'verfahren': 16052,
 '▁conclusion': 7489,
 '▁gezeigt': 22985,
 '▁drying': 16773,
 '▁répondre': 13122,
 'schmutz': 31877,
 '<extra_id_52>': 32047,
 '▁Gerne': 25247,
 'Schraub': 31976,
 '▁citi': 16545,
 '512': 24163,
 '▁brochure': 15535,
 '▁aprobat': 22667,
 '▁Natalie': 26983,
 '▁Materialien': 20636,
 'tischen': 13413,
 '▁Schatten': 30632,
 'spring': 14662,
 '▁Beyond': 13594,
 '▁unver': 13705,
 '▁Ty': 10352,
 '▁votre': 618,
 '▁exams': 14026,
 '▁domeniul': 9180,
 '▁unter': 1199,
 '▁traditional': 1435,
 'TIN': 25424,
 'extrait': 28739,
 '▁razor': 26828,
 'REN': 22413,
 'leton': 13248,
 'grilled': 19521,
 'FS': 7674,
 'thankfully': 29706,
 '▁resurse': 18113,
 '▁Hearing': 26651,
 '▁influence': 2860,
 '▁cam': 5511,
 'din': 2644,
 '▁pastel': 22678,
 '▁Luci': 11977,
 '▁route': 2981,
 'leaking': 26177,
 '126': 21976,
 '▁Bäume': 29401,
 '▁succeeded': 22399,
 '▁întâlnit': 28705,
 '▁spell': 10783,
 '▁shut': 6979,
 '▁donation': 9294,
 '▁tattoo': 16713,
 '▁hit': 1560,
 '▁Trojan': 28622,
 'isse': 3818,
 '▁breaches': 27358,
 '▁1914': 24725,
 '▁injection': 10672,
 'не': 14142,
 'Software': 29944,
 '▁citoyen': 17884,
 '▁boli': 12903,
 'doubtedly': 16501,
 '▁Termin': 10181,
 '▁religion': 5562,
 '▁găsi': 14488,
 'quelles': 17118,
 '▁ceux': 6023,
 'HER': 17444,
 'sstisch': 26137,
 '56': 4834,
 '▁spirit': 3564,
 '▁Manage': 19607,
 'people': 16588,
 'abilitate': 14511,
 '▁melt': 13297,
 'surgical': 31058,
 '▁mobiliz': 26169,
 ',"': 976,
 'beauftragte': 30082,
 '▁maximize': 11072,
 '▁prize': 6441,
 '▁miraculous': 30484,
 'emploi': 9767,
 'onformément': 31362,
 '▁flexibil': 23627,
 '▁window': 2034,
 'blood': 27798,
 '▁Ad': 1980,
 '▁Aplica': 29140,
 '(5)': 15757,
 '▁vér': 22397,
 '▁data': 331,
 '▁uncle': 20811,
 '▁Les': 622,
 'rained': 10761,
 'ificare': 8750,
 '▁Newton': 20126,
 '▁Tablet': 14571,
 'gazebo': 29903,
 '60': 3328,
 '▁swing': 7180,
 '▁controversy': 21760,
 '▁intens': 9608,
 '▁ruhig': 23582,
 '▁advanced': 2496,
 '▁instruments': 7778,
 '▁Jay': 9373,
 '▁Tickets': 11481,
 '▁baking': 6506,
 'spüren': 30796,
 'augmentation': 19260,
 'IDENT': 29433,
 '▁ventilation': 18426,
 'eria': 4476,
 '▁complaint': 10394,
 'pri': 2246,
 'gewiesen': 20409,
 '▁supliment': 27607,
 'raum': 6340,
 '▁topping': 19342,
 '▁allows': 1250,
 '▁restrictions': 9076,
 '▁planner': 13015,
 '▁reimburse': 29560,
 '▁hobbies': 27781,
 '▁ordered': 5563,
 '▁stability': 7606,
 '▁criterii': 28745,
 'Aus': 14934,
 '▁contained': 6966,
 '▁housing': 3499,
 '▁Stoff': 16016,
 '▁adaptée': 22022,
 'cette': 922,
 '▁feedback': 3160,
 'withstand': 23361,
 '▁long': 307,
 'producing': 30887,
 '▁epoxy': 30469,
 '▁Prima': 13425,
 '▁tastes': 13434,
 '▁resonate': 22771,
 'causing': 5885,
 '▁Divine': 20444,
 '▁emoti': 25993,
 '▁photographers': 16707,
 '▁Mall': 13552,
 'ART': 8241,
 '▁situatia': 24976,
 '▁contaminants': 30264,
 '▁nails': 17315,
 '▁congratulations': 29138,
 'treu': 17538,
 'IR': 5705,
 '▁courier': 27961,
 '▁acknowledge': 8406,
 '▁zurück': 4204,
 'öhl': 24430,
 '▁Drink': 20289,
 'bid': 9824,
 '▁goat': 18174,
 'par': 1893,
 '▁executed': 13763,
 'wind': 5165,
 '▁River': 2473,
 '▁Cuisine': 23406,
 '▁indication': 10369,
 'Städten': 31455,
 '▁precede': 21305,
 'schätzt': 27122,
 '▁Writing': 10237,
 '▁strengthened': 26390,
 'kö': 15898,
 '▁grams': 19847,
 '▁crochet': 20530,
 '▁căt': 8004,
 '▁confirmed': 5899,
 '▁strong': 1101,
 '▁petite': 6882,
 '▁Ausführung': 28513,
 '▁willing': 4403,
 'lässlich': 28564,
 '▁compliment': 12064,
 'izare': 5338,
 'füh': 25574,
 'lit': 4250,
 '▁yesterday': 4981,
 '▁réduction': 19673,
 '▁combine': 5148,
 '▁absence': 8605,
 '▁creep': 17463,
 '▁vedere': 5742,
 '▁Gray': 13375,
 'frying': 28455,
 'Visiting': 30338,
 '▁liking': 23340,
 '▁Register': 12306,
 '▁respectively': 6898,
 '▁vier': 7629,
 '▁downside': 21204,
 '▁studies': 2116,
 '▁larg': 13332,
 '▁action': 1041,
 '▁Catering': 29326,
 'Video': 25838,
 '▁Highly': 20600,
 '▁migration': 11661,
 '▁confusing': 15266,
 '▁erinnern': 25902,
 '▁bliss': 26078,
 '▁FIRST': 30085,
 '▁compose': 15283,
 '▁dividend': 12190,
 '▁Mak': 15666,
 '▁metres': 14604,
 '▁wedge': 22757,
 '▁simulation': 11108,
 '▁those': 273,
 '▁Offering': 22460,
 '▁item': 2118,
 '▁colaborare': 21446,
 '▁acquis': 25057,
 '▁Cruise': 15221,
 '▁Mich': 18463,
 '▁lieber': 20802,
 '▁prealabil': 25773,
 '▁débat': 19736,
 '▁Ca': 1336,
 '▁erst': 5248,
 'oreille': 24802,
 '▁mobilité': 29882,
 'suffisamment': 29269,
 '▁marijuana': 10434,
 '▁Brick': 21596,
 'duce': 12160,
 '▁încălc': 29616,
 '▁handset': 26331,
 '▁from': 45,
 '€': 3378,
 '▁Dawn': 21903,
 '▁titre': 8349,
 'на': 8194,
 'cino': 21919,
 '▁Bristol': 17836,
 '▁Incredible': 29332,
 '▁susțin': 29746,
 '▁considère': 31424,
 '▁acțiuni': 26824,
 'ching': 8509,
 '▁domeniu': 14690,
 '▁legal': 1281,
 '▁tuition': 15409,
 '▁since': 437,
 'ù': 23063,
 'izi': 10954,
 '▁department': 3066,
 '▁Hof': 17176,
 'tler': 14539,
 '▁YOUR': 11510,
 '▁activities': 1087,
 '▁Fifth': 26729,
 '▁lurk': 29503,
 '▁tug': 30274,
 '▁euro': 3983,
 '▁Sanctuary': 30021,
 'hardly': 10942,
 'effi': 23473,
 'HP': 13201,
 '▁fou': 21114,
 '▁culture': 1543,
 'pack': 5745,
 '4.8': 27441,
 '▁am': 183,
 '▁sandwiches': 20017,
 '▁encode': 23734,
 'sicherheit': 20170,
 '▁candles': 19490,
 '▁Sk': 6458,
 '▁prolong': 19556,
 '▁ressenti': 28387,
 '102': 14388,
 '▁crown': 10228,
 'Canada': 28811,
 '▁Sunny': 26827,
 '▁create': 482,
 '▁vegetation': 21780,
 'pression': 8243,
 '▁Scandinavia': 27700,
 '2.5': 15967,
 'ity': 485,
 '▁persistent': 15803,
 '▁trains': 14053,
 '▁credits': 11893,
 '▁Flint': 29612,
 '▁lie': 11761,
 '▁desk': 4808,
 'KU': 18519,
 'BJP': 28065,
 '▁wrote': 2832,
 '▁sights': 17458,
 '▁Carroll': 26508,
 'douceur': 28638,
 '▁conspir': 29105,
 '▁Claus': 22021,
 'cht': 3997,
 '▁unfamiliar': 24108,
 'jugé': 29790,
 '▁permettra': 16552,
 '▁darf': 10092,
 '▁Guvernului': 23487,
 '▁variat': 24855,
 '▁punch': 11462,
 '▁diabetes': 8363,
 '▁galaxy': 24856,
 'Strat': 19928,
 '▁combo': 15122,
 '▁climbing': 11908,
 '▁Kin': 13070,
 'та': 15517,
 '▁Correct': 28223,
 '▁Singh': 16738,
 '▁Chang': 24187,
 '▁bain': 7835,
 'Anschließend': 26916,
 'GIN': 24961,
 '▁pamper': 31094,
 'lag': 5430,
 'förder': 21872,
 '▁raw': 5902,
 '▁sauvegarde': 31741,
 '▁Flughafen': 24302,
 '▁Nürnberg': 28211,
 '▁visiting': 3644,
 '▁genes': 13485,
 '▁missed': 4785,
 '▁regim': 20536,
 '<extra_id_59>': 32040,
 '▁sentiment': 6493,
 '▁healthcare': 4640,
 'questioned': 21360,
 '▁pré': 2811,
 '▁longer': 1200,
 '▁copilului': 19627,
 'bung': 11848,
 'TG': 18943,
 'erra': 16841,
 '▁Gary': 13439,
 'muddy': 29736,
 'Totul': 28609,
 '▁retard': 19329,
 '▁Beleuchtung': 31760,
 '▁Democratic': 10021,
 'LF': 18962,
 '▁Lager': 16205,
 '▁sta': 3342,
 'aduse': 30834,
 '▁endeavor': 14310,
 '▁(2018)': 28068,
 '▁obstruction': 26359,
 'sterreich': 12852,
 '▁suplimentar': 26747,
 '/6': 18656,
 '▁F': 377,
 '▁Jur': 15598,
 '▁Ubuntu': 22998,
 '▁processed': 8534,
 '▁toate': 1785,
 'IV': 7589,
 'selon': 5928,
 '▁stand': 1518,
 '▁tenu': 17636,
 '▁extend': 4285,
 '▁întâlniri': 31011,
 '▁Surprise': 31237,
 '▁subconscious': 28872,
 'Dienstleistungen': 25121,
 '▁Jul': 17829,
 'ţional': 10563,
 'lichkeit': 9788,
 'liz': 13287,
 '▁Maybe': 3836,
 'browned': 31234,
 'Pad': 21853,
 'avons': 4123,
 '▁Dollar': 14110,
 'aki': 11259,
 '▁Burn': 10846,
 '▁Empire': 12187,
 '▁dafür': 5552,
 '▁productivity': 7596,
 '▁Market': 3611,
 'Time': 13368,
 '▁reliability': 10581,
 '▁Triple': 22709,
 'Class': 21486,
 '▁Italy': 5308,
 '▁closure': 12493,
 'ombre': 15729,
 '▁worthwhile': 20167,
 '▁linii': 26620,
 '▁rugged': 21350,
 'habitant': 29884,
 'leiste': 22075,
 '▁food': 542,
 '▁bumper': 23924,
 '▁ensure': 766,
 '▁finishing': 8619,
 '▁üblich': 28421,
 'RAD': 21577,
 '▁victorie': 19900,
 '▁suicide': 12259,
 '▁stellt': 9711,
 '▁couture': 29670,
 'APP': 13747,
 '▁eater': 23852,
 'ogram': 16275,
 '▁White': 1945,
 '▁Nissan': 19026,
 'vieux': 24913,
 'alia': 5434,
 '▁consortium': 27754,
 '▁botez': 27547,
 'Home': 19040,
 '▁festivals': 14856,
 '▁furniture': 1991,
 '▁shortly': 10545,
 '▁swimmer': 27424,
 'filmed': 25403,
 '▁Administration': 6863,
 'OT': 6951,
 'GH': 14100,
 'colour': 24814,
 '▁Client': 6371,
 '▁cracked': 21185,
 '▁Flood': 28391,
 '▁Europene': 18727,
 '▁lunar': 19920,
 '▁nascut': 29458,
 '▁Therapie': 20168,
 '▁capital': 1784,
 '▁disciples': 19424,
 'consulted': 29087,
 'NS': 7369,
 '▁present': 915,
 'vest': 19038,
 '▁dată': 9936,
 '▁entendu': 21481,
 '▁carrot': 15578,
 '▁Funeral': 21233,
 '▁Accident': 25553,
 '▁Permanent': 23996,
 '▁Cake': 17031,
 '▁vorgestellt': 23943,
 '▁urbain': 23364,
 '▁tread': 24735,
 '▁hack': 8093,
 '▁rock': 2480,
 '▁doll': 14295,
 '▁Inspector': 19773,
 '▁gerne': 5462,
 'dienst': 7691,
 'awaiting': 26312,
 'transport': 26803,
 '▁video': 671,
 'winning': 8163,
 '▁Lighting': 16714,
 '▁mancare': 24269,
 '▁Traian': 27423,
 '▁encouragement': 17427,
 '▁Atlantic': 9640,
 '▁Indoor': 25483,
 '▁Gegen': 5959,
 '▁listing': 6437,
 'benso': 28162,
 'rum': 2781,
 '▁continuous': 7558,
 '▁Veränderung': 19851,
 '▁Fiction': 24525,
 '▁mars': 8113,
 'countless': 11394,
 '▁legii': 20881,
 '▁frumos': 10317,
 '▁Levi': 16755,
 '▁causal': 31161,
 'contract': 20871,
 'plu': 12456,
 '▁Jaguar': 24457,
 'continent': 27339,
 'cios': 19029,
 'facerilor': 31359,
 'exhibiting': 30436,
 'ddling': 19955,
 '▁coaching': 7052,
 'SE': 4132,
 'Or': 7395,
 'hôte': 28610,
 'etro': 15252,
 'FD': 13916,
 '▁Heating': 24660,
 '▁airfare': 31793,
 'savory': 27802,
 'zukünftig': 23999,
 '▁encouraging': 9523,
 '▁Policies': 30959,
 'vermögen': 29954,
 '▁Archives': 18499,
 'longed': 23629,
 '=': 2423,
 '▁vocal': 6721,
 '▁cell': 2358,
 '▁charisma': 27439,
 '▁Gent': 21689,
 'Applicants': 26727,
 'echt': 12041,
 '▁Rev': 6342,
 '▁appointments': 14936,
 '▁replacing': 11906,
 '▁websites': 3395,
 'menée': 29283,
 'Occident': 30583,
 '▁Peace': 11128,
 '▁Effective': 18652,
 'scanned': 27011,
 '▁unlawful': 25487,
 '▁subscribers': 17303,
 '▁Bahrain': 29656,
 '▁showed': 3217,
 '▁evaluated': 14434,
 'dependent': 17631,
 'mel': 2341,
 '▁had': 141,
 '▁exterioar': 29338,
 '▁installed': 3029,
 'translates': 29213,
 '▁sketches': 27294,
 '▁Excel': 9506,
 'hid': 11740,
 '▁entwickelt': 10322,
 'Exista': 27750,
 'associe': 30675,
 '▁pièce': 14494,
 '▁Initiative': 12043,
 'vorsitzende': 31569,
 '▁Avenue': 6916,
 '▁entirety': 26771,
 '▁Asian': 6578,
 '▁Nova': 17259,
 'zumindest': 18885,
 '▁seminars': 19087,
 '▁co': 576,
 'мо': 21025,
 'Trader': 21923,
 '▁feu': 8703,
 '▁Pl': 7337,
 '▁NC': 9187,
 'Col': 9939,
 '▁module': 6008,
 '▁easy': 514,
 'tura': 7188,
 '▁affairs': 12748,
 'rise': 7854,
 '▁prea': 4745,
 'lebt': 13910,
 '▁Zi': 3969,
 '▁entitlement': 30053,
 '▁Zen': 9155,
 '▁Franco': 20439,
 '▁Gabriel': 11997,
 'нов': 31545,
 '▁Remove': 10002,
 'ismului': 22049,
 'er': 49,
 '▁vorbi': 24521,
 '▁obvious': 4813,
 '▁Multi': 4908,
 '▁Sigur': 28432,
 'heißt': 13172,
 '▁persoane': 3748,
 '20': 1755,
 '▁Schmerz': 22066,
 '▁Awareness': 25410,
 '222': 26144,
 '▁northwest': 24155,
 '▁Ring': 7888,
 '▁stubborn': 26629,
 '-2018': 20259,
 '▁Locat': 29315,
 '▁explic': 14323,
 'vas': 9856,
 'ania': 11219,
 'cola': 12600,
 'feed': 17012,
 '▁markets': 3212,
 '▁24,': 14320,
 '▁Cape': 9702,
 '▁pregatit': 23480,
 '▁feel': 473,
 '▁Wärme': 18193,
 '▁freut': 24537,
 '▁gewonnen': 23754,
 '▁cycles': 15164,
 '▁enjoyed': 2994,
 '▁longue': 12280,
 '▁perimeter': 26442,
 '▁graphics': 6484,
 '▁Hotel': 2282,
 'Control': 25716,
 '▁oraș': 12353,
 'Good': 20639,
 'connected': 19386,
 '▁Wick': 18602,
 '▁differentiation': 27910,
 '▁Cardinal': 21967,
 '▁tortilla': 25592,
 '▁embellish': 29018,
 'venue': 15098,
 '▁Ne': 1484,
 'town': 3540,
 'tail': 5756,
 '▁syrup': 15928,
 '▁envoyé': 23667,
 '▁breed': 8885,
 '▁50': 943,
 '▁Lancaster': 27830,
 '▁capacity': 2614,
 '▁aventur': 24089,
 '▁bench': 8453,
 '▁hurricane': 20818,
 'mut': 4246,
 '▁organizer': 14250,
 '▁Yale': 23501,
 '▁gelten': 13896,
 '▁satisfaction': 5044,
 '▁equality': 18963,
 '▁Maker': 18493,
 '▁tracking': 6418,
 '▁schöne': 11878,
 'itzer': 14777,
 '▁cerinte': 30219,
 'ylon': 25016,
 'MW': 16027,
 '▁edition': 4182,
 '▁gain': 2485,
 'hose': 9672,
 'focus': 25198,
 'ani': 2738,
 '▁Have': 2114,
 'fuses': 26951,
 '▁următor': 25935,
 '▁Arabic': 19248,
 'schen': 3878,
 '▁cruel': 23958,
 'utti': 31944,
 '▁stickers': 19239,
 'liche': 2626,
 '▁Felix': 23354,
 '▁advocat': 29945,
 '▁rising': 6937,
 '▁răs': 14675,
 '▁varsta': 18457,
 '▁unstable': 27644,
 '▁scăzut': 24794,
 'cott': 10405,
 '▁bible': 26996,
 'allowing': 3232,
 '▁an': 46,
 '▁Starting': 14362,
 'Tex': 13598,
 'ery': 4203,
 '▁etaj': 25056,
 'brow': 14853,
 '▁Einladung': 27509,
 '▁conquer': 24025,
 '▁protectie': 23376,
 '▁spate': 14911,
 '▁Kne': 22860,
 '▁Ford': 5222,
 '▁réservation': 25329,
 'bekannt': 27570,
 '▁SE': 5985,
 '▁reaction': 6363,
 '▁Zach': 22045,
 'intensive': 28135,
 '▁condiții': 19062,
 '▁live': 619,
 '▁give': 428,
 'pyr': 20455,
 'noch': 12555,
 'arbeitete': 31707,
 '▁tomorrow': 5721,
 '▁sympa': 17024,
 'izează': 16991,
 '▁Carpenter': 28337,
 '▁capable': 3919,
 'clés': 22169,
 '▁Tous': 14222,
 '▁singing': 8782,
 'entrepreneurship': 24849,
 '▁sulfur': 29090,
 '▁vet': 14065,
 'ali': 4288,
 'enia': 18242,
 '▁spoke': 5468,
 '▁Scripture': 17999,
 '▁sight': 6398,
 'ashi': 17155,
 '198': 24151,
 '▁sides': 4458,
 '▁stresses': 25375,
 'gutachten': 31515,
 '▁Way': 5994,
 'ătoare': 9097,
 '▁exist': 3223,
 'ruc': 11783,
 '▁actiune': 24866,
 '▁défend': 24211,
 '▁Hammer': 18812,
 '▁truc': 22159,
 'roc': 7818,
 'DH': 15538,
 '▁seniors': 14032,
 'peaks': 25399,
 '▁adevarat': 12813,
 '▁boat': 3432,
 '▁cheltuieli': 26245,
 '▁elevate': 25517,
 '▁market': 512,
 '▁adoptat': 25901,
 'Democrat': 19679,
 '▁revel': 26061,
 'thing': 8052,
 '▁rubber': 7859,
 '▁attract': 5521,
 'vis': 3466,
 '▁mere': 12143,
 'fabricated': 27066,
 '▁voiture': 9820,
 '▁acting': 6922,
 '▁ungefähr': 30400,
 '▁propriu': 14030,
 'AKE': 17253,
 'sol': 4099,
 '▁besondere': 7537,
 '▁aspect': 2663,
 'defined': 17094,
 '▁Hersteller': 13406,
 '▁Engine': 10612,
 '▁Prospect': 24383,
 '▁lower': 1364,
 'vir': 5771,
 '▁dolari': 20681,
 '▁update': 2270,
 '▁1975': 16312,
 'iscus': 28679,
 '▁personnage': 13989,
 'ooze': 27561,
 '▁issues': 807,
 '133': 22974,
 '▁muscular': 19671,
 '▁Delivery': 15715,
 '▁wurden': 3163,
 '▁Wright': 16634,
 'Westfalen': 31933,
 'zen': 1847,
 '▁Kirche': 17264,
 '▁renal': 23328,
 '▁Quality': 6495,
 'fiber': 27629,
 '▁cost': 583,
 '▁Von': 6560,
 '▁Hood': 19804,
 '▁Antarctic': 26461,
 'lutter': 20224,
 'affir': 27236,
 'ips': 15432,
 '▁treated': 4260,
 '▁cinq': 16109,
 '▁enthusiast': 26160,
 'lust': 10008,
 '▁Earl': 22101,
 'țiilor': 20249,
 '▁sophistication': 29244,
 '▁Orientierung': 31865,
 '▁tooth': 6290,
 '▁ihre': 1159,
 '▁South': 1013,
 '▁vedea': 11002,
 '▁giant': 6079,
 'ICE': 8906,
 '▁Puzzle': 29411,
 'leid': 21397,
 '▁messenger': 28110,
 'rait': 6893,
 '▁mail': 4842,
 '▁obs': 19963,
 '▁subscription': 7644,
 'zimmer': 11647,
 'lves': 8391,
 '▁nötig': 22195,
 '▁wipe': 16490,
 '▁clubs': 8122,
 '▁bacteria': 8710,
 '▁newsletter': 7288,
 'ches': 2951,
 '▁lush': 18127,
 '1-3': 16737,
 'asupra': 3880,
 '▁Mé': 10598,
 '▁Tochter': 23860,
 '▁waste': 2670,
 '▁hatch': 20618,
 'otte': 14708,
 '▁2019.': 4144,
 '▁Ideas': 6231,
 'Dame': 17084,
 '▁bass': 7981,
 '▁rejoice': 31418,
 '▁Manufacturing': 19193,
 '▁songs': 3605,
 '▁1942': 24466,
 '▁Planner': 27306,
 '▁idylli': 27602,
 '▁printemps': 24771,
 '▁pentru': 191,
 '▁pruning': 31858,
 'made': 4725,
 '▁Orange': 7311,
 '▁variables': 11445,
 'quaint': 24867,
 '▁negoci': 22797,
 '▁Drain': 15730,
 '▁Deep': 9509,
 'troisième': 20015,
 '▁militari': 26153,
 'abhängig': 19006,
 'designed': 15281,
 '▁cooperative': 20270,
 '▁shaping': 20266,
 '▁cleaned': 12631,
 '▁associate': 7573,
 '▁considerat': 14479,
 '▁outlets': 14290,
 'ador': 7923,
 '▁kindergarten': 23872,
 'mother': 21226,
 '▁Maryland': 10271,
 'vious': 19117,
 '2.7': 21280,
 '▁accessible': 3551,
 '▁south': 3414,
 '▁Contractor': 16858,
 '▁Diabetes': 23549,
 '▁lightly': 14292,
 '▁Geräte': 14766,
 '▁Mode': 9258,
 'ava': 8644,
 '▁Ré': 6272,
 '▁Division': 6022,
 'ver': 624,
 '▁Reef': 28972,
 '82': 4613,
 '▁Lit': 15507,
 'isch': 2499,
 '▁constituie': 21977,
 '▁inequality': 25608,
 '▁counting': 15899,
 '▁$8': 13155,
 'aimed': 8287,
 'http': 5948,
 '480': 20579,
 '▁Räume': 23389,
 '▁Traum': 16252,
 '▁strength': 2793,
 '12': 2122,
 '▁lucrari': 24148,
 'West': 19069,
 '▁Boutique': 26206,
 'process': 15056,
 'net': 1582,
 '▁fond': 3036,
 '▁Jag': 21520,
 '▁Single': 7871,
 '▁substrate': 17019,
 '▁divorce': 7759,
 '<extra_id_0>': 32099,
 '▁Surf': 18761,
 '▁Konzert': 20631,
 'uß': 6712,
 '▁Mau': 7758,
 '▁Pop': 5777,
 '▁possible': 487,
 '▁uncommon': 21141,
 '▁realitate': 16788,
 '▁examples': 4062,
 '360': 19208,
 '▁tables': 5056,
 '▁biseric': 11890,
 '▁next': 416,
 '▁confrunta': 28652,
 '▁vizite': 23297,
 '▁utiliza': 18187,
 '▁eingeladen': 27846,
 '▁sensor': 7824,
 '▁irrelevant': 26213,
 '71': 4450,
 '▁1920': 13978,
 'geschwindigkeit': 28053,
 '▁metabolic': 22044,
 '▁Produkt': 5389,
 'plastic': 24671,
 '▁degree': 1952,
 '▁Abschluss': 15951,
 '▁belongs': 16952,
 '▁buyer': 8001,
 '▁Berkeley': 20776,
 '▁erschien': 24072,
 '▁Chen': 15570,
 'DD': 11253,
 '▁viaţă': 19313,
 '▁racing': 8191,
 'frame': 11415,
 '▁warned': 15240,
 '▁equitable': 30364,
 '▁pellet': 25540,
 '▁Durchschnitt': 30335,
 '▁mural': 15848,
 '▁Member': 8541,
 'Practic': 24450,
 '▁verkauft': 23904,
 '▁innovant': 25780,
 'keit': 5754,
 '▁membrane': 13304,
 'trauen': 23937,
 'Appeals': 29641,
 '▁probable': 23093,
 '▁Karen': 14412,
 '▁thermostat': 22062,
 '▁vague': 15986,
 '▁Mental': 17054,
 '▁homework': 11920,
 'code': 4978,
 '▁depart': 15407,
 '▁Dupa': 10716,
 '▁Geschwindigkeit': 28694,
 '▁Schön': 18688,
 'EV': 8878,
 '▁Roland': 22613,
 '▁Receive': 24083,
 '$': 3229,
 '▁lock': 6081,
 '▁motivate': 18198,
 '▁equity': 8408,
 'Aici': 19845,
 '▁Elizabeth': 9066,
 '▁Z': 1027,
 '▁mother': 2039,
 'adjusting': 21604,
 '▁Cobb': 31546,
 '▁geography': 25055,
 'WE': 15713,
 '▁complète': 17534,
 '▁Brooklyn': 12805,
 '▁hydraulic': 20320,
 '▁shutter': 18094,
 '▁Available': 8144,
 '▁idle': 26592,
 'ografie': 21693,
 'aktuellen': 12309,
 '▁sportif': 23680,
 '▁Northwestern': 30198,
 'effective': 8993,
 '▁Irvine': 30411,
 '▁britanic': 27808,
 '▁partially': 14610,
 '▁selected': 2639,
 'gestiegen': 31451,
 'enţă': 17319,
 'inger': 9963,
 '▁portofoliu': 31674,
 '▁Kommentar': 19101,
 'dessus': 11613,
 '▁majoritatea': 16100,
 '▁Zauber': 31367,
 'MAP': 25790,
 '▁rencontrer': 22796,
 '▁fortunate': 14276,
 '▁Flickr': 29865,
 '▁Vent': 13713,
 '▁Virtu': 31180,
 '▁beaucoup': 3933,
 '▁exceptionnel': 28975,
 ...}

In [ ]:
print(ds['train']['text'][654])

## Introduction


English for Specific Purposes (E.S.P) courses form the foundation of English learning across various academic fields. Munoz-Liza and Taillefer (2018) highlight that (E.S.P) courses address  the  diverse  contextual  needs  of  different  audiences.  Basturkmen  (2006)  notes  that educators implement (E.S.P) in various countries and contexts.

Paltridge  and  Starfield  (2013)  describe  English  for  Academic  Purposes  (E.A.P)  as teaching English to learners who use the language for academic responsibilities. Stojkovi (2015) asserts that English has become the primary language of international communication in scientific and medical fields, linking people across various disciplines. Achievement tests in (E.S.P) courses are crucial for assessing course output and students' proficiency. Hutchinson and Waters (1987) and Hughes (2003) emphasize that (E.S.P) evaluates learners' proficiency and course objectives. According  to  Bachman  (1990),  test  scores  must  have  content  validity  to  be  meaningful, appropriate, and valuable. Kopriva (2008) adds that the clarity of test items influences students' performance. Thus, developing valid (E.M.P) achievement tests is critical for reflecting the proper standards of test takers. This study aims to assess the suitability of (E.M.P) achievement tests, examine if they meet the required criteria, and identify their strengths. The findings will benefit test designers, (E.S.P) and (E.M.P) experts, and applied linguistics professionals.

There are three primary issues the study aims to address .The first issue concerns whether Saudi  universities  align  English  for  Medical  Purposes    achievement  tests  with  the  skills, knowledge, and competencies required in the medical field.

The  second  issue  is  to  what  extent  instructors  perceive  these  tests  as  accurately reflecting the course content and meeting the needs of students in the medical domain. The third issue is that the potential gap between test content and instructional goals could hinder students' preparedness for real-world medical communication, resulting in suboptimal learning outcomes.

The study aims to:

Determine whether medical English tests adequately reflect the learning objectives of (E.M.P) courses and the specific language needs of medical students. This research is significant because:

- 1. Understanding content validity can help align tests with curriculum goals, ensuring they measure relevant skills effectively.
- 2. Accurate assessment can lead to better-targeted teaching strategies, improving students' professional readiness in English for medical contexts.
- 3. Findings  could  inform  policy  and  practice  in  developing  (E.M.P)    curricula  and assessments, particularly in a non-native English-speaking context like Saudi Arabia.
- 4. It addresses a specific need to evaluate and improve the quality of educational assessments in specialized English for Specific Purposes contexts.

The study is constructed to achieve the following objectives

- 1. Explore  instructors'  perceptions  of  the  alignment  between  (E.M.P)  achievement  test content and course objectives.
- 2. To assess whether the tests measure the practical and professional English skills required by medical students.
- 3. To identify any discrepancies or gaps in the test design from the instructors' perspectives.
- 4. To  provide  recommendations  for  improving  the  validity  and  reliability  of  (E,M.P) achievement tests.


## Literature Review


Dudley-Evans and St John (1998) state that educators design (E.S.P) courses to meet specific learners' needs, focusing on language use relevant to particular disciplines . Hutchinson and Waters (1987) argue that (E.S.P) courses should align with learners' needs, while Basturkmen (2006)  views  (E.S.P)  as  grounded  in  language  learning  and  teaching  principles.  Day  and Krzanowski (2011) note that ESP involves teaching the specific skills and language required for particular purposes. Paltridge and Starfield (2013) emphasize that ESP aids students in achieving academic, professional, and occupational goals. Hutchinson and Waters (1987) define a syllabus as  a  framework  that  specifies  learning  objectives  and  reflects  the  knowledge  learners  should acquire by the end of the course . Paltridge and Starfield (2013) differentiate (E.S,P) from English as  Second  Language  (E.S.L)  by  focusing  on  workplace  vocabulary  and  communication  skills. Hughes  (2003)  and  Harris  (1969)  suggest  that  assessments  should  include  tasks  reflecting candidates' actual abilities, including oral production samples such as pronunciation, grammar, and vocabulary.


## Definition and Purpose of Achievement Tests


Achievement tests measure students' knowledge and skills in specific subjects, reflecting their  academic  accomplishments.  These  tests  assess  instructional  effectiveness  and  students' learning outcomes, providing valuable feedback for educators (Nitko and Brookhart, 2014).


## Reliability and Validity of Achievement Tests


Practical achievement tests must demonstrate reliability and validity. Reliability ensures consistency of test results over time, while validity assesses whether the test measures what it is intended to measure (McMillan, 2014). Content validity, which involves aligning test content with the curriculum and instructional goals, is crucial for accurately reflecting what students have learned (Nunnally  and  Bernstein,  1994)  .  Experts  achieve  this  alignment  through  detailed  reviews  and comprehensive test blueprints (Downing, 2006).


## Alignment between Achievement Test Content and Learning Objectives


The  alignment  between  achievement  tests  and  learning  objectives  is  essential  for assessing educational program effectiveness (Biggs and Collis, 1982). Tests that closely align with course objectives provide a more accurate measure of students' skills (Linn and Gronlund, 2000).

www.awej.org

ISSN: 2229-9327

For EMP courses, this alignment ensures that assessments accurately measure intended medical  language  skills  (Taylor,  2004).  Recent  studies  emphasize  the  importance  of  content validity to ensure (E.M.P) tests align with learning objectives, covering specific medical contexts and terminology (Glickman and Arnett, 2022).Practical item analysis helps refine test content to match learning  outcomes  (Li  and  Zhao,  2021).  Integrating  curriculum  content  into  test  design ensures alignment with instructional goals (Chen and Wu, 2023). Holistic assessment approaches considering language proficiency and medical content knowledge are increasingly emphasized (Martinez Garcia, 2022). Feedback from stakeholders, including students and instructors, is crucial for ongoing test improvements (Kuo and Wong, 2024).


## (E.M.P) Test's Reflection of Practical Language Needs


(E.M.P) assessments must reflect the practical language tasks encountered in medical professionals'  daily  work  (Lu  and  Liang,  2021).  Tests  should  include  real-life  scenarios  and relevant  medical  terminology  to  ensure  applicability  to  professional  contexts  (Cao  et  al., 2022).Practical assessments incorporate scenarios and terminology pertinent to medical practice (Hodges,  2008;  Hyland,  2004),  evaluating  technical  vocabulary  and  communication  skills essential for patient and colleague interactions (West, 1994).


## Discrepancies between Test Content and Real-World Skills


Recent  research  identifies  gaps  between  EMP  test  content  and  the  language  skills required  in  medical  settings  (Chen  et  al.,  2023).  These  discrepancies  highlight  areas  for improvement in EMP courses and tests to better match professional communication complexities. Identifying these gaps is essential to refining test design and ensuring that EMP courses effectively prepare students for their roles (Bachman &amp; Palmer, 1996; Bachman, 2004).


## Factors Affecting Content Validity


Content validity remains a key concern, with factors such as course content representation, feedback mechanisms, and updates to current practices influencing it (Kane, 2019; Johnson  and  Brown,  2022).  Ensuring  that  EMP  tests  adapt  to  recent  changes  and  receive appropriate reviews is essential for maintaining validity and relevance (Adams and Taylor, 2021). Effective validation processes contribute to the reliability and relevance of EMP achievement tests (Messick, 1989; AERA, APA, and NCME, 2014).


## Previous Studies


The researcher reviewed six relevant studies.Siddiek (2010) found deficiencies in content validity in the Sudan School Certificate English Examinations, classifying them as proficiency tests rather than standardized achievement tests. Ibrahim (2016) identified a need for improved English  language  tests  for  Public  and  Environmental  Health  college  students,  emphasizing listening, speaking, reading, writing, vocabulary, grammar, and pronunciation. Mamaliga (2017) noted improvements in test content with modern approaches and real-life situations. Niu (2020) suggested that corpus-based resources could enhance creativity in ESP learning. Li and Heron (2021) found that medical students faced challenges in listening and speaking and desired to learn ESP through  medical  textbooks  from  their  first  year.  Umar  and  Ameen  (2022)  reported  high satisfaction with the content, layout, and design of the Nursing One textbook, which was deemed suitable for students' academic and professional needs.

www.awej.org

ISSN: 2229-9327

In recent years, the design, evaluation, and validation of English language assessments tailored to specific disciplines, such as medicine, have received significant attention, particularly in the Saudi Arabian context.

Jawhar et al. (2021) conducted a validation study of the English Language Entrance Test at King  Saud  bin  Abdulaziz  University  for  Health  Sciences  (KSAU-ET),  introducing  a comprehensive framework informed by leading validation models such as Messick (1996) and Weir (2005). The study emphasizes the value of creating in-house tests tailored to specific needs rather  than  relying  exclusively  on  standardized  assessments.  A  well-validated  entrance  exam ensures reliability and aligns more effectively with institutional goals . However, the authors call for  further  exploration  into  incorporating  additional  selection  criteria  and  gathering  broader evidence  to  strengthen  test  validation  processes.  Their  findings  are  critical  in  illustrating  the nuanced relationship between exam validity and its intended purpose.

Similarly, Al-Smadi et al. (2022) employed a linguistic ethnographic approach to explore the  identities  of  an  English  for  Medical  Purposes  (EMP)  teacher.  By  analyzing  classroom interactions, the study revealed the dynamic nature of teacher identities, ranging from expert to storyteller,  and  highlighted the implications of these shifts for student  engagement. While this research provides valuable insights into pedagogical practices and teacher-student dynamics, it indirectly  underscores  the  necessity  of  assessment  tools  that  reflect  the  multifaceted  nature  of teaching and learning within EMP contexts.

In the realm of instructional material evaluation, Umar and Ameen (2022) assessed the suitability of the Nursing One textbook used for premedical students at Umm-Al-Qura University. Their findings indicate that stakeholders view the textbook's content, layout, and organization as satisfactory and aligned with students' academic and professional needs. However, the authors stress the importance of rigorous evaluation processes for all English for Specific Purposes (E.S.P) textbooks to ensure they meet targeted learning outcomes effectively.

Collectively, these studies demonstrate progress in developing and evaluating (E.M.P) tools  in  the  Saudi  context  .  However,  a  research    gap  remains    in  understanding  instructors' perspectives  on  the  content  validity  of  (E.M.P)  achievement  tests.  While  prior  research  has primarily focused on validating entrance exams, teacher identities, and instructional materials, researchers  have  paid  little  attention  to  how  instructors  evaluate  these  tests'  effectiveness  in measuring learning outcomes and aligning with curricular goals. Addressing this gap could provide valuable  insights  for  refining  EMP  assessment  practices  and  enhancing  their  alignment  with pedagogical objectives.


## Methods


This study investigates instructors' perspectives on the content validity of English for Medical Purposes (EMP) achievement tests in Saudi universities. A Likert scale questionnaire was employed  by  the  researcher  as  the  primary  data  collection  tool,  targeting  32  instructors  from relevant academic institutions. The researchers designed the questionnaire to capture participants' evaluations  of  various  aspects  of  test  content  validity,  including  alignment  with  learning objectives, subject relevance, and comprehensiveness. Data analysis involved statistical methods to quantify the levels of agreement and identify trends in instructors' responses.


## Participants


The  study  systematically  selected  a  sample  of  32  instructors  from  the  broader population of English for Medical Purposes (E.M.P) educators at various universities in Saudi Arabia. The researchers used purposive sampling to select participants who met specific criteria relevant to the research objectives. These criteria included having at least five years of teaching experience, familiarity with the current (E.M.P) textbooks used in Saudi universities, and active involvement  in  teaching  English  for  Specific  Purposes  (E.S.P)  or  (E.M.P)  courses  during  the academic  year  2023/2024.  The  researchers  sent  participation  invitations  to  instructors  from  a diverse range of universities across the Kingdom of Saudi Arabia, where EMP courses are an integral part of the curriculum. The final selection ensured a representative sample of educators from  public  and  private  institutions,  capturing  a  broad  spectrum  of  teaching  experiences  and contexts.


## Research Instruments



## Questionnaire


The researcher administered a structured quantitative questionnaire, utilizing a 5-point Likert scale where strongly agree = 5, agree = 4, undecided = 3, disagree = 2, and strongly disagree =  1,  to  the  participants .  The  researcher  developed,  validated,  and  implemented  it  to  address research questions about participants' perceptions of the English for Medical Purposes (E.M.P) Achievement  test's  content  validity  at  Saudi  universities.This  questionnaire  comprised  four subscales aligned with research questions: alignment with course objectives, reflection of practical language needs, discrepancies with professional skills, and factors impacting content validity.The researcher displays the reliability and validity of the questionnaire  in tables 1 and 2 below.

Table 1. Reliability statistics of the questionnaire

Table 2. Validity statistics of the questionnaire


## Data Collection and Analysis Procedures


This  research  employed  a  descriptive-analytical  quantitative  approach.The  researcher collected the data  using a questionnaire distributed online to the selected (E.M.P) instructors. This method  efficiently  gathers  responses  from  a  geographically  dispersed  sample.  The  researcher analyzed  the  data  quantitatively  to  identify  patterns  and  insights  regarding  the  use  of  (E.M.P) textbooks and teaching practices.


## Results


This  study  explored  instructors'  perspectives  on  the  content  validity  of  English  for Medical  Purposes  (E.M.P)  achievement  tests  .The  discussion  addresses  four  key  research questions:  how  well  the  tests  align  with  course  objectives,  reflect  practical  language  needs, highlight discrepancies with professional skills, and identify factors impacting content validity.

www.awej.org

ISSN: 2229-9327


## Q.1Alignment with course objectives


The  data  indicates  a  generally  positive  perception  regarding  the  alignment  between (E.M.P)  test  content  and  course  objectives.Most  instructors  (81.9%)  either  strongly  agreed  or agreed  that  the  tests align  well  with  the  learning  objectives  of  (E.M.P)  courses  (Table Three)Appendix  B.  Instructors  generally  believe  that  (E.M.P)  achievement  tests  reflect  the intended course outcomes adequately . A small percentage of respondents (14.4%) disagreed or strongly  disagreed,  suggesting  concerns  about  misalignment.  This  disparity  underscores  the importance  of  regularly  reviewing  and  adjusting  test  content  to  align  it  with  changing  course objectives and teaching methods.


## Q.2 Reflection of practical language needs


When evaluating how well the (E.M.P) test content reflects the practical language needs of medical professionals, responses were more varied. While a majority of instructors (76.9%) agreed  or  strongly  agreed  that  the  tests  address  practical  needs  (Table  Four)Appendix  C,  a significant  portion  (16.9%)  expressed  concerns  by  disagreeing  or  strongly  disagreeing  . This variability suggests that while the tests meet practical needs, improvements are required to better reflect the specific language demands faced by medical professionals in practice.


## Q.3Discrepancies with professional skills


The  majority  of  instructors  (88.2%)  indicated  that  there  are  discrepancies  between (E.M.P) test content and the actual medical English skills required in professional settings (Table Five)Appendix D . This finding underscores a significant issue: the tests may not fully capture the complexities and nuances of medical English as used in professional contexts. The absence of intense disagreement among respondents highlights a consensus on this issue, suggesting an urgent need for revisions to better align test content with practical language skills required in the medical field

.

## Q.4 Factors impacting content validity.

Instructors  identified  various  factors  affecting  the  content  validity  of  EMP  tests.  The majority agreed that multiple factors contribute to content validity issues (67.0% when combining 'agree'  and  'strongly  agree'  responses  (Table  Six)  Appendix  E.  Commonly  cited  factors  might include the relevance of test content, the adequacy of test design, and the alignment with current medical  practices.  The  relatively  high  proportion  of  undecided  responses  (11.9%)  suggests uncertainties or varying opinions about which factors most significantly impact content validity.


## Discussion


The findings of this study provide critical insights into instructors' perspectives on the content validity and practical relevance of English for Medical Purposes (E.M.P) achievement tests. These findings support and sometimes extend the conclusions of previous research.

## Q.1 Alignment Between (E.M.P) Tests and Course Objectives

The results indicate that most instructors  perceive a strong alignment between (E.M.P) achievement test content and the learning objectives of (E.M.P) courses (81.9% agreement). This positive perception supports the view that these tests effectively reflect course goals. However, the concerns raised by a minority of respondents (14.4% disagreement) signal the need for periodic

www.awej.org

ISSN: 2229-9327


In [48]:
print(ds['train']['summary'][654])

Given the critical role of medical English in preparing students for real-world medical environments, this research is vital for ensuring that assessment tools accurately measure the competencies needed for effective communication in medical settings. The study addresses a significant research gap concerning aligning medical English tests with evolving medical language demands and professional practices. This study investigates instructors’ perspectives on the content validity of English for Medical Purposes achievement tests at universities in Saudi Arabia. It seeks answers to how instructors evaluate the alignment, relevance, and validity of English for Medical Purposes achievement test content concerning course objectives, professional language needs, and practical application. The researcher collected data using a structured questionnaire, which he distributed to 32 instructors with significant experience teaching Medical English textbooks. Findings reveal that while most instructors believe medical English tests align well with course objectives and address practical needs, they also identified discrepancies between test content and the required medical English skills . Continuous revisions and updates are necessary to ensure that assessments stay relevant and accurately reflect real-world medical language use, which enhances the effectiveness of training programs.

In [108]:
def preprocess_df(x):
    max_len = 1024
    head_len = 256
    end_len= max_len - head_len

    # Limpias texto
    x['text'] = [re.sub(r'\s+', ' ', str(t)) for t in x['text']]        # elimina espacios repetidos
    x['text'] = [re.sub(r'\n+', ' ', t) for t in x['text']]        # elimina saltos de línea
    x['text'] = [re.sub(r'[^\x00-\x7F]+', ' ', t) for t in x['text']]  # elimina caracteres raros

    # Limpias el resumen 
    x['summary'] = [re.sub(r'\s+', ' ', str(s)) for s in x['summary']]         # elimina espacios repetidos
    x['summary'] = [re.sub(r'\n+', ' ', s) for s in x['summary']]         # elimina saltos de línea
    x['summary'] = [re.sub(r'[^\x00-\x7F]+', ' ', s) for s in x['summary']]  # elimina caracteres raros


    # Tokenizas texto, truncation y padding en el DataCollator
    inputs = tokenizer(x['text'], truncation = False, padding=False)

    # Truncas manualmente
    input_ids_trunc = []
    attention_mask_trunc = []
    for ids in inputs['input_ids']:
        new_ids = ids[:head_len] + ids[-end_len:]
        input_ids_trunc.append(new_ids)
        attention_mask_trunc.append([1] * len(new_ids))

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(x['summary'], max_length=1024, truncation=True, padding=False)

    return ({
        'input_ids': input_ids_trunc,
        'attention_mask': attention_mask_trunc,
        'labels': labels['input_ids']
    })

In [109]:
ds_tokenized = ds.map(preprocess_df, batched=True, batch_size=32)

Map:   0%|          | 0/700 [00:00<?, ? examples/s]c:\Users\User\anaconda3\envs\nlp\lib\site-packages\transformers\tokenization_utils_base.py:4007: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(
Map: 100%|██████████| 700/700 [00:04<00:00, 165.49 examples/s]
Map: 100%|██████████| 300/300 [00:01<00:00, 160.76 examples/s]

In [91]:
ds_tokenized['train']['labels'][1]

[5289,
 4903,
 10,
 23869,
 7,
 1492,
 72,
 145,
 305,
 716,
 3,
 9,
 239,
 464,
 30,
 9885,
 1685,
 11392,
 41,
 427,
 11120,
 61,
 1002,
 11,
 72,
 145,
 46,
 1781,
 692,
 262,
 11120,
 4145,
 227,
 8,
 414,
 13,
 8,
 161,
 1135,
 5,
 25638,
 302,
 2116,
 43,
 4313,
 8,
 28879,
 1951,
 13,
 10981,
 262,
 11120,
 169,
 11,
 227,
 18,
 5842,
 7,
 161,
 6,
 379,
 10027,
 5958,
 670,
 6,
 10027,
 44,
 1788,
 1575,
 6,
 11,
 4141,
 16735,
 5,
 611,
 6,
 262,
 11120,
 97,
 19,
 59,
 3,
 18760,
 46,
 1215,
 5255,
 1162,
 2945,
 38,
 34,
 5619,
 30,
 10027,
 4742,
 3889,
 24,
 228,
 43,
 359,
 7763,
 7702,
 5,
 3,
 23500,
 6,
 1884,
 6678,
 65,
 59,
 1702,
 48,
 2859,
 17577,
 120,
 5,
 86,
 48,
 1040,
 6,
 62,
 9127,
 149,
 13768,
 31,
 16101,
 3055,
 30,
 116,
 12,
 1912,
 262,
 11120,
 4145,
 2603,
 10,
 5637,
 792,
 97,
 30,
 262,
 11120,
 11,
 6499,
 97,
 1869,
 227,
 161,
 5,
 7717,
 1863,
 87,
 20119,
 7,
 10,
 421,
 331,
 9418,
 300,
 209,
 9286,
 14936,
 45,
 3,
 4581,
 13768,
 45,
 3,
 9,
 508,
 16682,
 3721,
 1166,
 3712,
 6852,
 1745,
 5,
 421,
 17953,
 2579,
 3117,
 6,
 433,
 18,
 4563,
 97,
 7334,
 7,
 13,
 4141,
 13324,
 11,
 262,
 11120,
 169,
 5,
 101,
 253,
 24,
 8,
 1504,
 13,
 464,
 30,
 262,
 11120,
 1002,
 5619,
 30,
 823,
 8,
 161,
 19,
 612,
 274,
 42,
 227,
 46,
 4141,
 5,
 1266,
 18,
 9,
 102,
 2700,
 297,
 262,
 11120,
 161,
 1428,
 7,
 792,
 262,
 11120,
 22453,
 11,
 227,
 18,
 1981,
 716,
 1869,
 30,
 262,
 11120,
 5,
 1844,
 18,
 9,
 102,
 2700,
 297,
 262,
 11120,
 161,
 1428,
 7,
 227,
 18,
 1981,
 716,
 30,
 262,
 11120,
 68,
 5386,
 792,
 262,
 11120,
 97,
 5,
 101,
 253,
 24,
 3094,
 26592,
 97,
 344,
 14936,
 54,
 2454,
 321,
 554,
 18,
 11,
 442,
 18,
 9,
 102,
 2700,
 297,
 262,
 11120,
 161,
 5,
 3440,
 23,
 138,
 12418,
 10,
 421,
 772,
 59,
 163,
 199,
 178,
 734,
 8,
 9398,
 11,
 1809,
 13,
 161,
 30,
 6980,
 4145,
 6,
 72,
 2389,
 6,
 68,
 92,
 56,
 199,
 4640,
 17747,
 482,
 262,
 11120,
 16101,
 7,
 11,
 4141,
 2023,
 7,
 12,
 1428,
 10027,
 5958,
 670,
 1968,
 28,
 10981,
 262,
 11120,
 169,
 5,
 1]

In [116]:
training_args = Seq2SeqTrainingArguments(
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    generation_max_length=256,
    fp16=True  
)
data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer, model=model_name, padding=True, return_tensors='pt')

In [117]:
trainer = Seq2SeqTrainer(
    model,
    args = training_args,
    tokenizer = tokenizer,
    train_dataset=ds_tokenized['train'],
    eval_dataset=ds_tokenized['validation'],
    data_collator=data_collator
)

C:\Users\User\AppData\Local\Temp\ipykernel_1832\2483078581.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [118]:
trainer.train()

KeyboardInterrupt:

In [119]:
from torch.utils.data import DataLoader

def tokenize_test(x):
    max_len = 1024
    head_len = 256
    end_len = max_len - head_len

    x['text'] = [re.sub(r'\s+', ' ', str(t)) for t in x['text']]        # elimina espacios repetidos
    x['text'] = [re.sub(r'\n+', ' ', t) for t in x['text']]        # elimina saltos de línea
    x['text'] = [re.sub(r'[^\x00-\x7F]+', ' ', t) for t in x['text']]  # elimina caracteres raros

    inputs = tokenizer(x['text'], padding = False, truncation=False)

    input_ids_trunc, mask_attention_trunc = [], []
    for ids in inputs['input_ids']:
        new_ids = ids[:head_len] + ids[-end_len:]
        input_ids_trunc.append(new_ids)
        mask_attention_trunc.append([1] * len(new_ids))
    
    return ({
        'input_ids': input_ids_trunc,
        'attention_mask': mask_attention_trunc
    })

In [120]:
test_tokenized = test_ds.map(tokenize_test, batched=True)

Map: 100%|██████████| 345/345 [00:02<00:00, 169.46 examples/s]

In [121]:
test_tokenized = test_tokenized.remove_columns(['text'])

In [122]:
test_tokenized

Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 345
})

In [123]:
val_tokenized = validation_ds.map(tokenize_test, batched=True)
val_tokenized = val_tokenized.remove_columns(['text', 'summary'])

Map: 100%|██████████| 300/300 [00:01<00:00, 178.45 examples/s]

In [124]:
val_tokenized

Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 300
})

In [125]:
i = 0
ejemplo = val_tokenized[i]
ejemplo

{'input_ids': [0,
  48342,
  24474,
  9732,
  1472,
  1346,
  1033,
  9,
  285,
  2004,
  32,
  36550,
  30,
  10,
  2167,
  333,
  9,
  9553,
  47779,
  3115,
  14,
  33,
  57,
  11359,
  30,
  39061,
  21314,
  4,
  17356,
  4941,
  88,
  285,
  2004,
  19771,
  3489,
  109,
  45,
  14410,
  15,
  5,
  1291,
  227,
  19771,
  8,
  714,
  709,
  6,
  602,
  25,
  4159,
  5,
  592,
  1272,
  14,
  215,
  2004,
  1986,
  2519,
  7,
  4,
  152,
  1566,
  3891,
  6330,
  7,
  4442,
  2210,
  13144,
  30,
  634,
  25328,
  7930,
  579,
  36,
  23301,
  43,
  653,
  579,
  5,
  936,
  4625,
  7,
  28,
  116,
  36,
  771,
  4454,
  43,
  19771,
  1966,
  5448,
  6,
  61,
  16,
  17213,
  11,
  34495,
  438,
  34860,
  811,
  19771,
  1966,
  4,
  1398,
  6,
  305,
  4454,
  16,
  5049,
  7,
  5,
  289,
  5867,
  2981,
  2717,
  16730,
  36,
  13022,
  846,
  238,
  10,
  739,
  2660,
  5057,
  3225,
  1687,
  30,
  5,
  289,
  5867,
  2981,
  1080,
  7,
  42901,
  1233,
  14566,
  9,
  5,
  19618,
  4,
  305,
  4454,
  16,
  341,
  7,
  20489,
  762,
  15699,
  27890,
  624,
  5,
  1080,
  579,
  1982,
  2339,
  7,
  617,
  1346,
  5,
  1663,
  9,
  26,
  1437,
  1272,
  479,
  47385,
  289,
  11595,
  3411,
  24308,
  19137,
  42680,
  1398,
  6,
  38,
  694,
  10,
  4315,
  5377,
  9,
  5,
  7951,
  846,
  30,
  9311,
  1089,
  1676,
  2004,
  714,
  31,
  5,
  729,
  9,
  5,
  1824,
  10410,
  1621,
  7,
  5,
  1455,
  183,
  6,
  35105,
  5,
  709,
  31,
  5,
  10410,
  579,
  1437,
  1776,
  3930,
  1437,
  3020,
  7,
  5,
  289,
  5867,
  2981,
  2717,
  16730,
  4,
  38,
  67,
  1551,
  34495,
  438,
  34860,
  811,
  19020,
  21117,
  5213,
  6,
  61,
  4620,
  5,
  24456,
  9,
  127,
  5448,
  4,
  572,
  130,
  1724,
  9,
  745,
  24165,
  44887,
  1676,
  2004,
  31,
  5,
  618,
  12,
  20096,
  3567,
  35,
  6310,
  2911,
  23423,
  8,
  11734,
  5434,
  27366,
  11,
  121,
  35849,
  2331,
  6,
  6171,
  4,
  3574,
  359,
  3914,
  131,
  15309,
  4177,
  10486,
  6,
  820,
  1640,
  306,
  238,
  195,
  1898,
  195,
  4027,
  4,
  1205,
  640,
  39159,
  4,
  1957,
  73,
  698,
  4,
  41305,
  73,
  1570,
  33787,
  24406,
  4,
  10626,
  4,
  1549,
  2663,
  24990,
  20221,
  6,
  255,
  4,
  36,
  2464,
  322,
  20,
  26101,
  9,
  5,
  1437,
  12045,
  2587,
  4832,
  2585,
  33430,
  12986,
  18072,
  3258,
  8,
  5,
  987,
  2004,
  1486,
  4,
  20,
  35160,
  9779,
  5872,
  6,
  5138,
  1640,
  306,
  238,
  290,
  4718,
  290,
  6750,
  4,
  1205,
  640,
  39159,
  4,
  1957,
  73,
  698,
  4,
  1225,
  4718,
  73,
  33490,
  2940,
  2481,
  21369,
  33416,
  36860,
  255,
  1584,
  1641,
  6,
  83,
  482,
  359,
  3914,
  131,
  11628,
  687,
  5282,
  6,
  272,
  4,
  36,
  844,
  2146,
  322,
  11183,
  718,
  3009,
  25328,
  7930,
  579,
  99,
  579,
  5,
  936,
  4625,
  7,
  28,
  116,
  36,
  771,
  4454,
  43,
  1548,
  7,
  28399,
  632,
  334,
  21009,
  714,
  11,
  1156,
  8,
  3430,
  35,
  10,
  1006,
  1246,
  4,
  1016,
  3642,
  9,
  1624,
  359,
  3914,
  131,
  16410,
  11,
  3061,
  6,
  321,
  1640,
  288,
  238,
  112,
  508,
  4,
  1205,
  640,
  39159,
  4,
  1957,
  73,
  698,
  4,
  41305,
  73,
  29221,
  3272,
  2518,
  1000,
  4,
  844,
  2146,
  4,
  30586,
  4111,
  1096,
  5869,
  6,
  289,
  482,
  22553,
  6,
  248,
  482,
  22327,
  636,
  10461,
  6,
  256,
  482,
  359,
  3914,
  131,
  19878,
  6852,
  6,
  83,
  4,
  36,
  32701,
  322,
  1832,
  4879,
  33077,
  8864,
  1477,
  285,
  474,
  8,
  1888,
  474,
  36667,
  116,
  83,
  37423,
  9,
  5,
  1283,
  31,
  987,
  714,
  8,
  1524,
  36,
  34499,
  4482,
  322,
  3642,
  9,
  42443,
  17129,
  359,
  3914,
  131,
  2573,
  1309,
  6,
  1191,
  1640,
  176,
  238,
  13955,
  12312,
  4,
  1205,
  640,
  39159,
  4,
  1957,
  73,
  698,
  4,
  1225,
  3367,
  73,
  267,
  7529,
  4,
  32857,
  4,
  288,
  3170,
  37634,
  10812,
  8132,
  2822,
  9730,
  6,
  11611,
  32297,
  272,
  9788,
  6,
  359,
  3914,
  131,
  221,
  1344,
  1342,
  256,
  32781,
  4,
  36,
  14420,
  102,
  322,
  289,
  5867,
  2981,
  2717,
  16730,
  2090,
  11109,
  4,
  289,
  5867,
  2981,
  19618,
  1080,
  4,
  1205,
  640,
  1401,
  4,
  4691,
  11282,
  4,
  298,
  5867,
  2981,
  4,
  7354,
  4,
  1350,
  73,
  37447,
  30179,
  73,
  29,
  38828,
  6232,
  73,
  996,
  698,
  2517,
  207,
  844,
  13022,
  846,
  207,
  844,
  17167,
  9309,
  9482,
  207,
  844,
  250,
  134,
  207,
  844,
  12,
  207,
  844,
  18562,
  207,
  844,
  38834,
  207,
  844,
  15110,
  207,
  844,
  21747,
  4,
  31494,
  10812,
  8132,
  2822,
  9730,
  6,
  11611,
  32297,
  272,
  9788,
  6,
  359,
  3914,
  131,
  221,
  1344,
  1342,
  256,
  32781,
  4,
  36,
  14420,
  428,
  322,
  289,
  5867,
  2981,
  2717,
  16730,
  2090,
  11109,
  40643,
  112,
  4713,
  43885,
  4,
  289,
  5867,
  2981,
  19618,
  1080,
  4,
  1205,
  640,
  1401,
  4,
  4691,
  11282,
  4,
  298,
  5867,
  2981,
  4,
  7354,
  4,
  1350,
  73,
  37447,
  30179,
  73,
  29,
  38828,
  4531,
  73,
  996,
  698,
  2517,
  207,
  844,
  13022,
  846,
  207,
  844,
  17167,
  9309,
  9482,
  207,
  16295,
  207,
  844,
  12,
  207,
  844,
  41376,
  207,
  844,
  48522,
  4,
  31494,
  10812,
  8132,
  2822,
  9730,
  6,
  11611,
  32297,
  272,
  9788,
  6,
  359,
  3914,
  131,
  221,
  1344,
  1342,
  256,
  32781,
  4,
  36,
  14420,
  438,
  322,
  289,
  5867,
  2981,
  2717,
  16730,
  2090,
  11109,
  40643,
  155,
  13559,
  26709,
  5213,
  4,
  289,
  5867,
  2981,
  19618,
  1080,
  4,
  1205,
  640,
  1401,
  4,
  4691,
  11282,
  4,
  298,
  5867,
  2981,
  4,
  7354,
  4,
  1350,
  73,
  37447,
  30179,
  73,
  29,
  38828,
  4531,
  73,
  996,
  698,
  2517,
  207,
  844,
  13022,
  846,
  207,
  844,
  17167,
  9309,
  9482,
  207,
  16295,
  207,
  844,
  12,
  207,
  844,
  41376,
  207,
  844,
  48522,
  4,
  31494,
  10812,
  8132,
  2822,
  9730,
  6,
  11611,
  32297,
  272,
  9788,
  6,
  359,
  3914,
  131,
  221,
  1344,
  1342,
  256,
  32781,
  4,
  36,
  14420,
  417,
  322,
  289,
  5867,
  2981,
  2717,
  16730,
  2090,
  11109,
  40643,
  204,
  11109,
  9307,
  4,
  289,
  5867,
  2981,
  19618,
  1080,
  4,
  305,
  1043,
  39064,
  6,
  226,
  482,
  20221,
  6,
  255,
  482,
  359,
  3914,
  131,
  15738,
  3578,
  6,
  468,
  4,
  163,
  4,
  36,
  16310,
  322,
  42243,
  17707,
  312,
  45319,
  1938,
  11,
  5828,
  4,
  9356,
  8,
  9619,
  83,
  35,
  15735,
  8,
  5374,
  6,
  4059,
  1640,
  401,
  238,
  316,
  3083,
  45576,
  4,
  1205,
  640,
  39159,
  4,
  1957,
  73,
  698,
  4,
  698,
  4671,
  73,
  102,
  306,
  36101,
  1899,
  18989,
  6,
  221,
  4,
  36,
  844,
  2146,
  322,
  9730,
  34514,
  1258,
  8,
  3139,
  19020,
  2533,
  4189,
  35,
  1909,
  8160,
  6,
  6067,
  8,
  96,
  43119,
  11,
  928,
  4,
  6275,
  977,
  4,
  13804,
  6,
  229,
  4,
  36,
  3789,
  6,
  902,
  706,
  322,
  2615,
  289,
  5867,
  2981,
  579,
  2004,
  709,
  1155,
  694,
  10,
  403,
  892,
  11,
  2660,
  16186,
  116,
  21988,
  111,
  11068,
  29,
  4,
  1205,
  640,
  24635,
  4,
  29,
  4393,
  1334,
  4,
  1957,
  4,
  1350,
  73,
  3789,
  73,
  4197,
  73,
  7424,
  12,
  298,
  5867,
  242,
  2459,
  12,
  ...],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  ...]}

In [126]:
loader = DataLoader(
    [ejemplo],
    batch_size=1,
    collate_fn=lambda x: tokenizer.pad(x, return_tensors="pt")
)

for batch in loader:
    batch = {k: v.to(trainer.model.device) for k, v in batch.items() if k in ["input_ids", "attention_mask"]}
    outputs = trainer.model.generate(**batch, max_length=1024)
    decoded = trainer.tokenizer.batch_decode(outputs, skip_special_tokens=True)

You're using a BartTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

In [127]:
print(decoded)

['This article seeks to extend existing literature by using Bacchi s (2009) What s the problem represented to be? (WPR) discourse analysis method, which is rooted in Foucauldian discourse analysis. WPR is used to uncover key rationalisations within the Council s written documents to further understand the construction of said  problems . Here, I provide a brief context of the HDV by reviewing British council housing policy from the election of the 2010 Coalition Government to the present day, tracing the development from the Coalition s  Big Society  programme to the Haringey Development Vehicle. I also review Foucaudian Discourse Analysis, which forms the backbone of my method. After three decades of building decommodified council housing from the post-War era: Displacement and dispossessions in Uppsala, Sweden. (2006). Do urban regeneration programmes improve public health and reduce health inequalities? A synthesis of the evidence from UK policy and practice (1980 2004). Journal of Epidemiology &amp; Community Health, 60(2), 108 115.']

In [128]:
print(validation_ds['summary'][i])

Conventional interpretations of public and social housing—embedded in wider neoliberal and capitalist discourses—are not just ‘out there’, existing on their own. In fact, they are constructed by specific forces within and without political discourse. Existing work on public housing policy generally ignores the relationship between policy development and discourse, thereby taking the social problems addressed by such policies as natural and granted. By critically interrogating lodged assumptions, uncovering underlying theories, and peeling back the layers of discourse, this work builds on existing literature by using Bacchi’s What’s the problem represented to be? (WPR) discourse analysis method, which has its roots in Foucauldian discourse analysis. Used in housing studies and other domains, WPR is here applied to the Haringey Development Vehicle (HDV), a £2 billion joint venture considered by the Haringey Council, which was intended to regenerate significant portions of the Borough. WPR is used to uncover key rationalisations within the Council’s written documents. In doing so, the following topics are discussed, among others: governmentality, marketisation and privatisation, and neoliberal problematisations. Finally, this study investigates the complicated relationship between history, policy, and discourse.

In [129]:
trainer.evaluate()

KeyboardInterrupt: